services:
  web:
    restart: always
    build:
      dockerfile: Dockerfile.prod
    depends_on:
      - pg
      - minio
    environment:
      - MIX_ENV=prod
      - PHX_HOST=${PHX_HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=ecto://postgres:postgres@pg/justrunit
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  pg:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  minio:
    restart: always
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  miniodata:
