services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - pg
      - minio
    environment:
      - PHX_HOST
      - SECRET_KEY_BASE
      - DATABASE_URL
      - MINIO_URL
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY

  pg:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    volumes:
      - miniodata:/tmp/minio_data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  miniodata:
