services:
  web:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    depends_on:
      - pg
      - minio
    environment:
      - MIX_ENV=dev
      - PHX_HOST=localhost
      - SECRET_KEY_BASE=DElG+3akCkNp+QmIx3kmvmjXMUni6zLZU5n9B9sF++u+4J+EfiOsxYGpzYqkyrh+
      - DATABASE_URL=ecto://postgres:postgres@pg/justrunit
      - AWS_ENDPOINT_URL_S3=s3://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    volumes:
      - .:/app
      - /app/deps
      - /app/_build

  pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=justrunit_dev
    volumes:
      - pgdata:/tmp/pg_data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/tmp/minio_data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data --console-address ":9001"

  setup_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add jri_minio http://minio:9000 minioadmin minioadmin &&
      /usr/bin/mc mb jri_minio/justrunit &&
      /usr/bin/mc policy download jri_minio/justrunit &&
      exit 0
      "

volumes:
  pgdata:
  miniodata:
